# Generated by Django 4.0.5 on 2022-06-13 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='participants',
            new_name='participant',
        ),
    ]
